# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: state.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bstate.proto\x12\x05state\"\x1f\n\x0eTriggerRequest\x12\r\n\x05state\x18\x01 \x01(\t\"\"\n\x0fTriggerResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32J\n\x0cStateMachine\x12:\n\x07trigger\x12\x15.state.TriggerRequest\x1a\x16.state.TriggerResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'state_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_TRIGGERREQUEST']._serialized_start=22
  _globals['_TRIGGERREQUEST']._serialized_end=53
  _globals['_TRIGGERRESPONSE']._serialized_start=55
  _globals['_TRIGGERRESPONSE']._serialized_end=89
  _globals['_STATEMACHINE']._serialized_start=91
  _globals['_STATEMACHINE']._serialized_end=165
# @@protoc_insertion_point(module_scope)
