# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import state_pb2 as state__pb2


class StateMachineStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.trigger = channel.unary_unary(
                '/state.StateMachine/trigger',
                request_serializer=state__pb2.TriggerRequest.SerializeToString,
                response_deserializer=state__pb2.TriggerResponse.FromString,
                )


class StateMachineServicer(object):
    """Missing associated documentation comment in .proto file."""

    def trigger(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_StateMachineServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'trigger': grpc.unary_unary_rpc_method_handler(
                    servicer.trigger,
                    request_deserializer=state__pb2.TriggerRequest.FromString,
                    response_serializer=state__pb2.TriggerResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'state.StateMachine', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class StateMachine(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def trigger(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/state.StateMachine/trigger',
            state__pb2.TriggerRequest.SerializeToString,
            state__pb2.TriggerResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
